name: face-recognition-gpu
channels:
  - conda-forge
  - cudawarped
  - defaults
dependencies:
  - cudatoolkit=11.2
  - cudnn=8.1
  - pip=25.1
  - python=3.9
  - pip:
      - opencv-contrib-python==4.8.0.74
      - pyserial==3.5
      - mediapipe==0.10.5
      - tensorflow==2.8
      - protobuf==3.20
      - numpy==1.26.4